import os
from pygame.locals import *

UNIT = 25
H_UNITS = 16
V_UNITS = 20
LEFT_BUFFER = 50
RIGHT_BUFFER = 50
CEILING_BUFFER = 50
FLOOR_BUFFER = 100

def get_h_unit_x_val(h_unit):
    return h_unit * UNIT + LEFT_BUFFER

def get_v_unit_y_val(v_unit):
    return v_unit * UNIT + CEILING_BUFFER

PLAY_WIDTH = UNIT * H_UNITS
PLAY_HEIGHT = UNIT * V_UNITS

LEFT_WALL = LEFT_BUFFER
RIGHT_WALL = LEFT_BUFFER + PLAY_WIDTH
CEILING = CEILING_BUFFER
FLOOR = CEILING_BUFFER + PLAY_HEIGHT
H_MIDDLE = (PLAY_WIDTH / 2) + LEFT_BUFFER
V_MIDDLE = (PLAY_HEIGHT / 2) + CEILING_BUFFER

WINDOW_WIDTH = PLAY_WIDTH + LEFT_BUFFER + RIGHT_BUFFER
WINDOW_HEIGHT = PLAY_HEIGHT + CEILING_BUFFER + FLOOR_BUFFER
MAIN_WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

IMAGE_DIR = os.path.join(os.path.split(os.path.abspath(__file__))[0], 'images')

SPECIAL_TYPES = {'NONE': None}

MAX_PLAYERS = 3

FIRE_DELAY = 0.25
FAST_FIRE_DELAY = 0.17

P1_MOVEMENT_KEYS = [K_w, K_s, K_a, K_d]
P2_MOVEMENT_KEYS = [K_i, K_k, K_j, K_l]
P3_MOVEMENT_KEYS = [K_UP, K_DOWN, K_LEFT, K_RIGHT]


BULLET_SCALE = [14,14]
ENEMY_SCALE = [25,25]
NORMAL_SCALE = [41,41]

PLAYER_GUN_1_SPEED = [0,-12]
